version: 2
updates:
  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "CI"
      - "dependencies"

  # Keep Julia packages up to date
  - package-ecosystem: "julia"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "Julia"
      - "dependencies"

  # Keep Rust/Cargo dependencies up to date
  - package-ecosystem: "cargo"
    directory: "/amalthea"
    schedule:
      interval: "monthly"
    labels:
      - "Rust"
      - "dependencies"
